// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createInput, renderWith } from "obix-core-component";
export { createInput } from "obix-core-component";
export type { AutocompleteValue, InputConfig, InputState, InputType, ValidationState, ValidationTiming } from "obix-core-component";
export const renderInput = renderWith(createInput);
